/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Crackwall: typeof import('./src/components/Crackwall.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCanvas: typeof import('./src/components/TheCanvas.vue')['default']
    ToggleDark: typeof import('./src/components/ToggleDark.vue')['default']
  }
}
